name: tevalearn_miniapp
description: TevaLearn LMS MiniApp.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  redis: ^3.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.6.18
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.2.5
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  webview_flutter: ^4.7.0
  iframe_view: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
