name: tevalearn_miniapp
description: TevaLearn LMS MiniApp.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  redis: ^3.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  markdown: ^7.0.0
  universal_html: ^2.2.4
  webview_flutter_android: ^3.8.0
  webview_flutter_wkwebview: ^3.8.0
  webview_flutter_platform_interface: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
